###############################################################################
# Role: OpenShiftMaster                                                            #
###############################################################################
- name: OpenShiftMaster
  description: |
    OpenShiftMaster role
  CountDefault: 1
  RoleParametersDefault:
    OpenShiftNodeGroupName: 'node-config-master'
    DockerSkipUpdateReconfiguration: true
  tags:
    - primary
    - controller
    - openshift
  networks:
    - External
    - InternalApi
    - Storage
  # For systems with both IPv4 and IPv6, you may specify a gateway network for
  # each, such as ['ControlPlane', 'External']
  default_route_networks: ['External']
  ServicesDefault:
    - OS::TripleO::Services::ContainerImagePrepare
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::HAproxy
    - OS::TripleO::Services::Keepalived
    - OS::TripleO::Services::Ntp
    - OS::TripleO::Services::OpenShift::Master
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::TripleoFirewall
    - OS::TripleO::Services::TripleoPackages
