###############################################################################
# Role: OpenShiftWorker                                                            #
###############################################################################
- name: OpenShiftWorker
  description: |
    OpenShiftWorker role
  CountDefault: 1
  RoleParametersDefault:
    OpenShiftNodeGroupName: 'node-config-compute'
    DockerSkipUpdateReconfiguration: true
  tags:
    - openshift
  networks:
    - InternalApi
    - Storage
  # For systems with both IPv4 and IPv6, you may specify a gateway network for
  # each, such as ['ControlPlane', 'External']
  default_route_networks: ['ControlPlane']
  ServicesDefault:
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::Ntp
    - OS::TripleO::Services::OpenShift::GlusterFS
    - OS::TripleO::Services::OpenShift::Worker
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::TripleoFirewall
