# A Heat environment file which can be used to enable a
# Cinder NVMeOF backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendNVMeOF: ../puppet/services/cinder-backend-nvmeof.yaml

parameter_defaults:
  CinderNVMeOFBackendName: 'tripleo_nvmeof'
  CinderNVMeOFTargetPort: 4460
  CinderNVMeOFTargetHelper: 'nvmet'
  CinderNVMeOFTargetProtocol: 'nvmet_rdma'
  CinderNVMeOFTargetPrefix: 'nvme-subsystem'
  CinderNVMeOFTargetPortId: 1
  CinderNVMeOFTargetNameSpaceId: 10

  ControllerParameters:
    ExtraKernelModules:
      nvmet: {}
      nvmet-rdma: {}
  ComputeParameters:
    ExtraKernelModules:
      nvme: {}
      nvme-rdma: {}
