# DEPRECATED: these mappings are now the default in
# overcloud-resource-registry-puppet.j2.yaml. This environment file will be
# removed during the Stein release.
resource_registry:
  OS::TripleO::SoftwareDeployment: ../config-download-structured.yaml

  OS::Heat::SoftwareDeployment: ../config-download-software.yaml
  OS::Heat::StructuredDeployment: ../config-download-structured.yaml

  OS::TripleO::DeploymentSteps: OS::Heat::None
  OS::TripleO::WorkflowSteps: OS::Heat::None

  OS::TripleO::Ssh::KnownHostsDeployment: OS::Heat::None
  OS::TripleO::Ssh::HostPubKey: OS::Heat::None
