# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Configure Designate Parameters
# description: |
#   Sample configuration parameters for Designate.  Requires the
#   enable-designate environment.
parameter_defaults:
  # The content for Designate's pools.yaml
  # Mandatory. This parameter must be set by the user.
  # Type: string
  DesignatePools: |
    - name: default
      # The name is immutable. There will be no option to change the name after
      # creation and the only way will to change it will be to delete it
      # (and all zones associated with it) and recreate it.
      description: Default Pool

      attributes: {}

      # List out the NS records for zones hosted within this pool
      # This should be a record that is created outside of designate, that
      # points to the public IP of the controller node.
      ns_records:
        - hostname: ns1-1.example.org.
          priority: 1

      # List out the nameservers for this pool. These are the actual BIND servers.
      # We use these to verify changes have propagated to all nameservers.
      nameservers:
        - host: 10.0.0.51
          port: 53

      # List out the targets for this pool. For BIND there will be one
      # entry for each BIND server, as we have to run rndc command on each server
      targets:
        - type: bind9
          description: BIND9 Server 1

          # List out the designate-mdns servers from which BIND servers should
          # request zone transfers (AXFRs) from.
          # This should be the IP of the controller node.
          # If you have multiple controllers you can add multiple masters
          # by running designate-mdns on them, and adding them here.
          masters:
            - host: 10.0.0.51
              port: 5354

          # BIND Configuration options
          options:
            host: 10.0.0.51
            port: 53
            rndc_host: 172.17.0.251
            rndc_port: 953
            rndc_key_file: /etc/rndc.key

  # If True, enable the internal Neutron DNS server that provides name
  # resolution between VMs.  This parameter has no effect if
  # NeutronDhcpAgentDnsmasqDnsServers is set.
  # Type: boolean
  NeutronEnableInternalDNS: True

  # Comma-separated list of extensions enabled for the Neutron plugin.
  # Type: comma_delimited_list
  NeutronPluginExtensions: qos,port_security,dns

