# Deprecated as config-download is now the default.
resource_registry:
  OS::TripleO::SoftwareDeployment: OS::Heat::StructuredDeployment
  OS::TripleO::Ssh::HostPubKey: ../extraconfig/tasks/ssh/host_public_key.yaml
  OS::TripleO::Ssh::KnownHostsDeployment: OS::Heat::StructuredDeployments
  OS::TripleO::DeploymentSteps: OS::Heat::StructuredDeploymentGroup

  # Used only for config-download deployment, for non-config-download deployment,
  # PreNetworkConfig (host-config-and-reboot.yaml) stack will handle it.
  OS::TripleO::Services::BootParams: OS::Heat::None
  OS::TripleO::Reboot::SoftwareDeployment: OS::TripleO::SoftwareDeployment
