heat_template_version: rocky

description: >
  OpenStack Designate Central service configured with Puppet
parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionDesignateCentral:
    default: 'overcloud-designate-central'
    type: string
  DesignateCentralLoggingSource:
    type: json
    default:
      tag: openstack.designate.central
      path: /var/log/designate/designate-central.log
  DesignateWorkers:
    default: 0
    description: Number of workers for Designate services.
    type: number
  DesignatePassword:
    description: The password for the Designate's database account.
    type: string
    hidden: true
  DesignatePools:
    description: The content for Designate's pools.yaml
    type: string

conditions:
  designate_workers_zero: {equals : [{get_param: DesignateWorkers}, 0]}

resources:
  DesignateBase:
    type: ./designate-base.yaml
    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Designate Central service.
    value:
      service_name: designate_central
      monitoring_subscription: {get_param: MonitoringSubscriptionDesignateCentral}
      logging_source: {get_param: DesignateCentralLoggingSource}
      logging_groups:
        - designate
      config_settings:
        map_merge:
        - get_attr: [DesignateBase, role_data, config_settings]
        - tripleo::profile::base::designate::central::pools_file_content: {get_param: DesignatePools}
          designate::db::database_connection:
            make_url:
              scheme: {get_param: [EndpointMap, MysqlInternal, protocol]}
              username: designate
              password: {get_param: DesignatePassword}
              host: {get_param: [EndpointMap, MysqlInternal, host]}
              path: /designate
              query:
                read_default_file: /etc/my.cnf.d/tripleo.cnf
                read_default_group: tripleo
        -
          if:
          - designate_workers_zero
          - {}
          - designate::central::workers: {get_param: DesignateWorkers}
      step_config: |
        include tripleo::profile::base::designate::central
      service_config_settings:
        mysql:
          designate::db::mysql::password: {get_param: DesignatePassword}
          designate::db::mysql::user: designate
          designate::db::mysql::host: {get_param: [EndpointMap, MysqlInternal, host_nobrackets]}
          designate::db::mysql::dbname: designate
          designate::db::mysql::allowed_hosts:
            - '%'
            - "%{hiera('mysql_bind_host')}"
