heat_template_version: rocky

description: >
  Openstack Manila base service. Shared by manila-api/scheduler/share services

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ManilaIPv6:
    default: False
    description: Set to True to enable IPv6 access in manila.
    type: boolean
  Debug:
    default: false
    description: Set to True to enable debugging on all services.
    type: boolean
  ManilaDebug:
    default: ''
    description: Set to True to enable debugging Manila services.
    type: string
    constraints:
      - allowed_values: [ '', 'true', 'True', 'TRUE', 'false', 'False', 'FALSE']
  ManilaPassword:
    description: The password for the manila service account.
    type: string
    hidden: true
  NotificationDriver:
    type: string
    default: 'messagingv2'
    description: Driver or drivers to handle sending notifications.
    constraints:
      - allowed_values: [ 'messagingv2', 'noop' ]
  RpcPort:
    default: 5672
    description: The network port for messaging backend
    type: number
  RpcUserName:
    default: guest
    description: The username for messaging backend
    type: string
  RpcPassword:
    description: The password for messaging backend
    type: string
    hidden: true
  RpcUseSSL:
    default: false
    description: >
        Messaging client subscriber parameter to specify
        an SSL connection to the messaging host.
    type: string

conditions:
  service_debug_unset: {equals : [{get_param: ManilaDebug}, '']}
  manila_ipv6: {equals : [{get_param: ManilaIPv6}, true]}

outputs:
  role_data:
    description: Role data for the Manila Base service.
    value:
      service_name: manila_base
      config_settings:
        manila::notification_driver: {get_param: NotificationDriver}
        # TODO(ansmith): remove once p-t-o switches to oslo params
        manila::rabbit_userid: {get_param: RpcUserName}
        manila::rabbit_password: {get_param: RpcPassword}
        manila::rabbit_use_ssl: {get_param: RpcUseSSL}
        manila::rabbit_port: {get_param: RpcPort}
        manila::debug:
          if:
          - service_debug_unset
          - {get_param: Debug }
          - {get_param: ManilaDebug }
        manila::db::database_db_max_retries: -1
        manila::db::database_max_retries: -1
        manila::sql_connection:
          make_url:
            scheme: {get_param: [EndpointMap, MysqlInternal, protocol]}
            username: manila
            password: {get_param: ManilaPassword}
            host: {get_param: [EndpointMap, MysqlInternal, host]}
            path: /manila
            query:
              read_default_file: /etc/my.cnf.d/tripleo.cnf
              read_default_group: tripleo
        manila::network::neutron::network_plugin_ipv6_enabled: {get_param: ManilaIPv6}
        # Currently the address family parameters are mutually exclusive
        manila::network::neutron::network_plugin_ipv4_enabled: {if: ["manila_ipv6", false, true]}
      service_config_settings:
        mysql:
          manila::db::mysql::password: {get_param: ManilaPassword}
          manila::db::mysql::user: manila
          manila::db::mysql::host: {get_param: [EndpointMap, MysqlInternal, host_nobrackets]}
          manila::db::mysql::dbname: manila
          manila::db::mysql::allowed_hosts:
            - '%'
            - "%{hiera('mysql_bind_host')}"
