heat_template_version: rocky

description: >
  OpenStack Sahara base service. Shared for all Sahara services.

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  SaharaPassword:
    description: The password for the sahara service account, used by sahara-api.
    type: string
    hidden: true
  Debug:
    type: boolean
    default: false
    description: Set to True to enable debugging on all services.
  SaharaDebug:
    default: ''
    description: Set to True to enable debugging Sahara services.
    type: string
    constraints:
      - allowed_values: [ '', 'true', 'True', 'TRUE', 'false', 'False', 'FALSE']
  SaharaPlugins:
    default: ["ambari","cdh","mapr"]
    description: Sahara enabled plugin list
    type: comma_delimited_list
  NotificationDriver:
    type: string
    default: 'messagingv2'
    description: Driver or drivers to handle sending notifications.
    constraints:
      - allowed_values: [ 'messagingv2', 'noop' ]
  RpcPort:
    default: 5672
    description: The network port for messaging backend
    type: number
  RpcUserName:
    default: guest
    description: The username for messaging backend
    type: string
  RpcPassword:
    description: The password for messaging backend
    type: string
    hidden: true
  RpcUseSSL:
    default: false
    description: >
        Messaging client subscriber parameter to specify
        an SSL connection to the messaging host.
    type: string

conditions:
  service_debug_unset: {equals : [{get_param: SaharaDebug}, '']}

outputs:
  role_data:
    description: Role data for the Sahara base service.
    value:
      service_name: sahara_base
      config_settings:
        sahara::database_connection:
          make_url:
            scheme: {get_param: [EndpointMap, MysqlInternal, protocol]}
            username: sahara
            password: {get_param: SaharaPassword}
            host: {get_param: [EndpointMap, MysqlInternal, host]}
            path: /sahara
            query:
              read_default_file: /etc/my.cnf.d/tripleo.cnf
              read_default_group: tripleo
        sahara::notify::notification_driver: {get_param: NotificationDriver}
        # TODO(ansmith): remove once p-t-o switches to oslo params
        sahara::rabbit_password: {get_param: RpcPassword}
        sahara::rabbit_user: {get_param: RpcUserName}
        sahara::rabbit_use_ssl: {get_param: RpcUseSSL}
        sahara::rabbit_port: {get_param: RpcPort}
        sahara::debug:
          if:
          - service_debug_unset
          - {get_param: Debug }
          - {get_param: SaharaDebug }
        # Remove admin_password when https://review.openstack.org/442619 is merged.
        sahara::admin_password: {get_param: SaharaPassword}
        sahara::use_neutron: true
        sahara::plugins: {get_param: SaharaPlugins}
        sahara::rpc_backend: rabbit
        sahara::db::database_db_max_retries: -1
        sahara::db::database_max_retries: -1
        sahara::keystone::authtoken::www_authenticate_uri: {get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]}
        sahara::keystone::authtoken::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]}
        sahara::keystone::authtoken::auth_url: {get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]}
        sahara::keystone::authtoken::password: {get_param: SaharaPassword}
        sahara::keystone::authtoken::project_name: 'service'
