heat_template_version: rocky

description: >
  Qpid dispatch router service for messaging RPCs configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  RpcPort:
    default: 5672
    description: The network port for messaging backend
    type: number
  RpcUserName:
    default: guest
    description: The username for messaging backend
    type: string
  RpcPassword:
    description: The password for messaging backend
    type: string
    hidden: true
  RpcUseSSL:
    default: false
    description: >
        Messaging client subscriber parameter to specify
        an SSL connection to the messaging host.
    type: string

resources:
  QdrouterdServiceBase:
    type: ../qdr.yaml
    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the OsloMessagingRpc role.
    value:
      service_name: oslo_messaging_rpc
      monitoring_subscription: {get_attr: [QdrouterdServiceBase, role_data, monitoring_subscription]}
      global_config_settings:
        map_merge:
          - get_attr: [QdrouterdServiceBase, role_data, global_config_settings]
          - oslo_messaging_rpc_scheme: amqp
            oslo_messaging_rpc_user_name: {get_param: RpcUserName}
            oslo_messaging_rpc_password: {get_param: RpcPassword}
            oslo_messaging_rpc_use_ssl: {get_param: RpcUseSSL}
            oslo_messaging_rpc_port: {get_param: RpcPort}
      config_settings:
        map_merge:
          - get_attr: [QdrouterdServiceBase, role_data, config_settings]
          - tripleo.oslo_messaging_rpc.firewall_rules:
              '109 qdrouterd':
                dport:
                  - {get_param: RpcPort}
                  - 31459
                  - 31460
            qdr::listener_addr:
              str_replace:
                template:
                  "%{hiera('$NETWORK')}"
                params:
                  $NETWORK: {get_param: [ServiceNetMap, OsloMessagingRpcNetwork]}
            tripleo::profile::base::qdr::qdr_listener_port: {get_param: RpcPort}
            tripleo::profile::base::qdr::qdr_username: {get_param: RpcUserName}
            tripleo::profile::base::qdr::qdr_password: {get_param: RpcPassword}
      step_config: |
        include ::tripleo::profile::base::qdr
