resource_registry:
  OS::TripleO::Services::SkydiveAnalyzer: ../../extraconfig/services/skydive-analyzer.yaml
  OS::TripleO::Services::SkydiveAgent: ../../extraconfig/services/skydive-agent.yaml

#parameter_defaults:
#  SkydiveVars:
#    globals:
#      skydive_listen_ip: 0.0.0.0
#    analyzers:
#      skydive_analyzer_docker_command: "analyzer"
#    agents:
#      skydive_analyzer_docker_command: "agent"
