heat_template_version: rocky

description: >
  Pre-deployment for the TripleO undercloud

parameters:
  server:
    type: string

resources:

  UndercloudPreConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: ./undercloud_pre.sh}

  UndercloudPreDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: UndercloudPreDeployment
      server:  {get_param: server}
      config: {get_resource: UndercloudPreConfig}
