heat_template_version: rocky

description: >
  Ceph Metadata service.

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CephMdsKey:
    description: The cephx key for the MDS service. Can be created
                 with ceph-authtool --gen-print-key.
    type: string
    hidden: true
  ManilaCephFSDataPoolName:
    default: manila_data
    type: string
  ManilaCephFSDataPoolPGNum:
    default: 128
    type: number
  ManilaCephFSMetadataPoolName:
    default: manila_metadata
    type: string
  ManilaCephFSMetadataPoolPGNum:
    default: 128
    type: number
  ManilaCephFSShareBackendName:
    default: cephfs
    type: string

resources:
  CephBase:
    type: ./ceph-base.yaml
    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

  CephMdsAnsibleVars:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        vars:
          cephfs_data: {get_param: ManilaCephFSDataPoolName}
          cephfs_metadata: {get_param: ManilaCephFSMetadataPoolName}
          cephfs: {get_param: ManilaCephFSShareBackendName}
          cephfs_pools:
          - { name: {get_param: ManilaCephFSDataPoolName}, pgs: {get_param: ManilaCephFSDataPoolPGNum} }
          - { name: {get_param: ManilaCephFSMetadataPoolName}, pgs: {get_param: ManilaCephFSMetadataPoolPGNum} }

outputs:
  role_data:
    description: Role data for the Ceph Metadata service.
    value:
      service_name: ceph_mds
      upgrade_tasks: []
      puppet_config:
        config_image: ''
        config_volume: ''
        step_config: ''
      docker_config: {}
      external_deploy_tasks:
        list_concat:
        - {get_attr: [CephBase, role_data, external_deploy_tasks]}
        - - name: ceph_mds_external_deploy_init
            when: step == '1'
            tags: ceph
            block:
              - name: set ceph-ansible group vars mdss
                set_fact:
                  ceph_ansible_group_vars_mdss: {get_attr: [CephMdsAnsibleVars, value, vars]}
              - name: generate ceph-ansible group vars mdss
                copy:
                  dest: "{{playbook_dir}}/ceph-ansible/group_vars/mdss.yml"
                  content: "{{ceph_ansible_group_vars_mdss|to_nice_yaml}}"
      external_update_tasks: {get_attr: [CephBase, role_data, external_update_tasks]}
      external_upgrade_tasks: {get_attr: [CephBase, role_data, external_upgrade_tasks]}
      config_settings:
        map_merge:
        - tripleo.ceph_mds.firewall_rules:
            '112 ceph_mds':
              dport:
              - '6800-7300'
        - {}
